def generate_config(config_vars):
    config_lines = [
        "/* Configuration for OnStepX */",
        "",
        "// CONTROLLER",
        f"#define PINMAP                        {config_vars['PINMAP']}",
        f"#define SERIAL_A_BAUD_DEFAULT        {config_vars['SERIAL_A_BAUD_DEFAULT']}",
        f"#define SERIAL_B_BAUD_DEFAULT        {config_vars['SERIAL_B_BAUD_DEFAULT']}",
        f"#define SERIAL_B_ESP_FLASHING         {config_vars['SERIAL_B_ESP_FLASHING']}",
        f"#define SERIAL_C_BAUD_DEFAULT        {config_vars['SERIAL_C_BAUD_DEFAULT']}",
        f"#define SERIAL_D_BAUD_DEFAULT        {config_vars['SERIAL_D_BAUD_DEFAULT']}",
        f"#define SERIAL_E_BAUD_DEFAULT        {config_vars['SERIAL_E_BAUD_DEFAULT']}",
        f"#define SERIAL_RADIO                  {config_vars['SERIAL_RADIO']}",
        f"#define WIFI_MODULE                  {config_vars['WIFI_MODULE']}",
        f"#define STATUS_LED                    {config_vars['STATUS_LED']}",
        f"#define RETICLE_LED_DEFAULT           {config_vars['RETICLE_LED_DEFAULT']}",
        f"#define RETICLE_LED_MEMORY            {config_vars['RETICLE_LED_MEMORY']}",
        f"#define RETICLE_LED_INVERT            {config_vars['RETICLE_LED_INVERT']}",
        f"#define WEATHER                       {config_vars['WEATHER']}",
        f"#define STEP_WAVE_FORM                {config_vars['STEP_WAVE_FORM']}",
        f"#define NV_DRIVER                     {config_vars['NV_DRIVER']}",
        "",
        "// MOUNT",
        f"#define AXIS1_DRIVER_MODEL            {config_vars['AXIS1_DRIVER_MODEL']}",
        f"#define AXIS1_STEPS_PER_DEGREE       {config_vars['AXIS1_STEPS_PER_DEGREE']}",
        f"#define AXIS1_REVERSE                 {config_vars['AXIS1_REVERSE']}",
        f"#define AXIS1_LIMIT_MIN              {config_vars['AXIS1_LIMIT_MIN']}",
        f"#define AXIS1_LIMIT_MAX              {config_vars['AXIS1_LIMIT_MAX']}",
        f"#define AXIS1_DRIVER_MICROSTEPS      {config_vars['AXIS1_DRIVER_MICROSTEPS']}",
        f"#define AXIS1_DRIVER_MICROSTEPS_GOTO {config_vars['AXIS1_DRIVER_MICROSTEPS_GOTO']}",
        f"#define AXIS1_DRIVER_IHOLD           {config_vars['AXIS1_DRIVER_IHOLD']}",
        f"#define AXIS1_DRIVER_IRUN            {config_vars['AXIS1_DRIVER_IRUN']}",
        f"#define AXIS1_DRIVER_IGOTO           {config_vars['AXIS1_DRIVER_IGOTO']}",
        f"#define AXIS1_DRIVER_STATUS          {config_vars['AXIS1_DRIVER_STATUS']}",
        f"#define AXIS1_DRIVER_DECAY           {config_vars['AXIS1_DRIVER_DECAY']}",
        f"#define AXIS1_DRIVER_DECAY_GOTO      {config_vars['AXIS1_DRIVER_DECAY_GOTO']}",
        f"#define AXIS1_POWER_DOWN             {config_vars['AXIS1_POWER_DOWN']}",
        f"#define AXIS1_SENSE_HOME             {config_vars['AXIS1_SENSE_HOME']}",
        f"#define AXIS1_SENSE_LIMIT_MIN        {config_vars['AXIS1_SENSE_LIMIT_MIN']}",
        f"#define AXIS1_SENSE_LIMIT_MAX        {config_vars['AXIS1_SENSE_LIMIT_MAX']}",
        "",
        f"#define AXIS2_DRIVER_MODEL            {config_vars['AXIS2_DRIVER_MODEL']}",
        f"#define AXIS2_STEPS_PER_DEGREE       {config_vars['AXIS2_STEPS_PER_DEGREE']}",
        f"#define AXIS2_REVERSE                 {config_vars['AXIS2_REVERSE']}",
        f"#define AXIS2_LIMIT_MIN              {config_vars['AXIS2_LIMIT_MIN']}",
        f"#define AXIS2_LIMIT_MAX              {config_vars['AXIS2_LIMIT_MAX']}",
        f"#define AXIS2_DRIVER_MICROSTEPS      {config_vars['AXIS2_DRIVER_MICROSTEPS']}",
        f"#define AXIS2_DRIVER_MICROSTEPS_GOTO {config_vars['AXIS2_DRIVER_MICROSTEPS_GOTO']}",
        f"#define AXIS2_DRIVER_IHOLD           {config_vars['AXIS2_DRIVER_IHOLD']}",
        f"#define AXIS2_DRIVER_IRUN            {config_vars['AXIS2_DRIVER_IRUN']}",
        f"#define AXIS2_DRIVER_IGOTO           {config_vars['AXIS2_DRIVER_IGOTO']}",
        f"#define AXIS2_DRIVER_STATUS          {config_vars['AXIS2_DRIVER_STATUS']}",
        f"#define AXIS2_DRIVER_DECAY           {config_vars['AXIS2_DRIVER_DECAY']}",
        f"#define AXIS2_DRIVER_DECAY_GOTO      {config_vars['AXIS2_DRIVER_DECAY_GOTO']}",
        f"#define AXIS2_POWER_DOWN             {config_vars['AXIS2_POWER_DOWN']}",
        f"#define AXIS2_SENSE_HOME             {config_vars['AXIS2_SENSE_HOME']}",
        f"#define AXIS2_SENSE_LIMIT_MIN        {config_vars['AXIS2_SENSE_LIMIT_MIN']}",
        f"#define AXIS2_SENSE_LIMIT_MAX        {config_vars['AXIS2_SENSE_LIMIT_MAX']}",
        "",
        f"#define MOUNT_TYPE                    {config_vars['MOUNT_TYPE']}",
        f"#define MOUNT_COORDS                  {config_vars['MOUNT_COORDS']}",
        f"#define MOUNT_COORDS_MEMORY           {config_vars['MOUNT_COORDS_MEMORY']}",
        f"#define MOUNT_ENABLE_IN_STANDBY       {config_vars['MOUNT_ENABLE_IN_STANDBY']}",
        f"#define TIME_LOCATION_SOURCE          {config_vars['TIME_LOCATION_SOURCE']}",
        f"#define TIME_LOCATION_PPS_SENSE       {config_vars['TIME_LOCATION_PPS_SENSE']}",
        f"#define STATUS_MOUNT_LED             {config_vars['STATUS_MOUNT_LED']}",
        f"#define STATUS_BUZZER                {config_vars['STATUS_BUZZER']}",
        f"#define STATUS_BUZZER_DEFAULT        {config_vars['STATUS_BUZZER_DEFAULT']}",
        f"#define STATUS_BUZZER_MEMORY         {config_vars['STATUS_BUZZER_MEMORY']}",
        f"#define ST4_INTERFACE                {config_vars['ST4_INTERFACE']}",
        f"#define ST4_HAND_CONTROL             {config_vars['ST4_HAND_CONTROL']}",
        f"#define ST4_HAND_CONTROL_FOCUSER     {config_vars['ST4_HAND_CONTROL_FOCUSER']}",
        f"#define GUIDE_TIME_LIMIT             {config_vars['GUIDE_TIME_LIMIT']}",
        f"#define GUIDE_DISABLE_BACKLASH       {config_vars['GUIDE_DISABLE_BACKLASH']}",
        f"#define LIMIT_SENSE                  {config_vars['LIMIT_SENSE']}",
        f"#define LIMIT_STRICT                 {config_vars['LIMIT_STRICT']}",
        f"#define PARK_SENSE                   {config_vars['PARK_SENSE']}",
        f"#define PARK_SIGNAL                  {config_vars['PARK_SIGNAL']}",
        f"#define PARK_STATUS                  {config_vars['PARK_STATUS']}",
        f"#define PARK_STRICT                  {config_vars['PARK_STRICT']}",
        f"#define PEC_STEPS_PER_WORM_ROTATION  {config_vars['PEC_STEPS_PER_WORM_ROTATION']}",
        f"#define PEC_SENSE                    {config_vars['PEC_SENSE']}",
        f"#define PEC_BUFFER_SIZE_LIMIT        {config_vars['PEC_BUFFER_SIZE_LIMIT']}",
        f"#define TRACK_BACKLASH_RATE          {config_vars['TRACK_BACKLASH_RATE']}",
        f"#define TRACK_AUTOSTART              {config_vars['TRACK_AUTOSTART']}",
        f"#define TRACK_COMPENSATION_DEFAULT   {config_vars['TRACK_COMPENSATION_DEFAULT']}",
        f"#define TRACK_COMPENSATION_MEMORY    {config_vars['TRACK_COMPENSATION_MEMORY']}",
        f"#define SLEW_RATE_BASE_DESIRED       {config_vars['SLEW_RATE_BASE_DESIRED']}",
        f"#define SLEW_RATE_MEMORY             {config_vars['SLEW_RATE_MEMORY']}",
        f"#define SLEW_ACCELERATION_DIST       {config_vars['SLEW_ACCELERATION_DIST']}",
        f"#define SLEW_RAPID_STOP_DIST         {config_vars['SLEW_RAPID_STOP_DIST']}",
        f"#define GOTO_FEATURE                 {config_vars['GOTO_FEATURE']}",
        f"#define GOTO_OFFSET                  {config_vars['GOTO_OFFSET']}",
        f"#define GOTO_OFFSET_ALIGN            {config_vars['GOTO_OFFSET_ALIGN']}",
        f"#define MFLIP_SKIP_HOME              {config_vars['MFLIP_SKIP_HOME']}",
        f"#define MFLIP_AUTOMATIC_DEFAULT      {config_vars['MFLIP_AUTOMATIC_DEFAULT']}",
        f"#define MFLIP_AUTOMATIC_MEMORY       {config_vars['MFLIP_AUTOMATIC_MEMORY']}",
        f"#define MFLIP_PAUSE_HOME_DEFAULT     {config_vars['MFLIP_PAUSE_HOME_DEFAULT']}",
        f"#define MFLIP_PAUSE_HOME_MEMORY      {config_vars['MFLIP_PAUSE_HOME_MEMORY']}",
        f"#define PIER_SIDE_SYNC_CHANGE_SIDES  {config_vars['PIER_SIDE_SYNC_CHANGE_SIDES']}",
        f"#define PIER_SIDE_PREFERRED_DEFAULT  {config_vars['PIER_SIDE_PREFERRED_DEFAULT']}",
        f"#define PIER_SIDE_PREFERRED_MEMORY   {config_vars['PIER_SIDE_PREFERRED_MEMORY']}",
        f"#define ALIGN_AUTO_HOME              {config_vars['ALIGN_AUTO_HOME']}",
        f"#define ALIGN_MODEL_MEMORY           {config_vars['ALIGN_MODEL_MEMORY']}",
        f"#define ALIGN_MAX_STARS              {config_vars['ALIGN_MAX_STARS']}",
        "",
        "// ROTATOR",
        f"#define AXIS3_DRIVER_MODEL            {config_vars['AXIS3_DRIVER_MODEL']}",
        f"#define AXIS3_SLEW_RATE_BASE_DESIRED {config_vars['AXIS3_SLEW_RATE_BASE_DESIRED']}",
        f"#define AXIS3_STEPS_PER_DEGREE       {config_vars['AXIS3_STEPS_PER_DEGREE']}",
        f"#define AXIS3_REVERSE                 {config_vars['AXIS3_REVERSE']}",
        f"#define AXIS3_LIMIT_MIN              {config_vars['AXIS3_LIMIT_MIN']}",
        f"#define AXIS3_LIMIT_MAX              {config_vars['AXIS3_LIMIT_MAX']}",
        f"#define AXIS3_DRIVER_MICROSTEPS      {config_vars['AXIS3_DRIVER_MICROSTEPS']}",
        f"#define AXIS3_DRIVER_MICROSTEPS_GOTO {config_vars['AXIS3_DRIVER_MICROSTEPS_GOTO']}",
        f"#define AXIS3_DRIVER_IHOLD           {config_vars['AXIS3_DRIVER_IHOLD']}",
        f"#define AXIS3_DRIVER_IRUN            {config_vars['AXIS3_DRIVER_IRUN']}",
        f"#define AXIS3_DRIVER_IGOTO           {config_vars['AXIS3_DRIVER_IGOTO']}",
        f"#define AXIS3_DRIVER_STATUS          {config_vars['AXIS3_DRIVER_STATUS']}",
        f"#define AXIS3_DRIVER_DECAY           {config_vars['AXIS3_DRIVER_DECAY']}",
        f"#define AXIS3_DRIVER_DECAY_GOTO      {config_vars['AXIS3_DRIVER_DECAY_GOTO']}",
        f"#define AXIS3_POWER_DOWN             {config_vars['AXIS3_POWER_DOWN']}",
        f"#define AXIS3_SENSE_HOME             {config_vars['AXIS3_SENSE_HOME']}",
        f"#define AXIS3_SENSE_LIMIT_MIN        {config_vars['AXIS3_SENSE_LIMIT_MIN']}",
        f"#define AXIS3_SENSE_LIMIT_MAX        {config_vars['AXIS3_SENSE_LIMIT_MAX']}",
        "",
        "// FOCUSERS",
        f"#define AXIS4_DRIVER_MODEL            {config_vars['AXIS4_DRIVER_MODEL']}",
        f"#define AXIS4_SLEW_RATE_BASE_DESIRED {config_vars['AXIS4_SLEW_RATE_BASE_DESIRED']}",
        f"#define AXIS4_SLEW_RATE_MINIMUM      {config_vars['AXIS4_SLEW_RATE_MINIMUM']}",
        f"#define AXIS4_STEPS_PER_MICRON       {config_vars['AXIS4_STEPS_PER_MICRON']}",
        f"#define AXIS4_REVERSE                 {config_vars['AXIS4_REVERSE']}",
        f"#define AXIS4_LIMIT_MIN              {config_vars['AXIS4_LIMIT_MIN']}",
        f"#define AXIS4_LIMIT_MAX              {config_vars['AXIS4_LIMIT_MAX']}",
        f"#define AXIS4_DRIVER_MICROSTEPS      {config_vars['AXIS4_DRIVER_MICROSTEPS']}",
        f"#define AXIS4_DRIVER_MICROSTEPS_GOTO {config_vars['AXIS4_DRIVER_MICROSTEPS_GOTO']}",
        f"#define AXIS4_DRIVER_IHOLD           {config_vars['AXIS4_DRIVER_IHOLD']}",
        f"#define AXIS4_DRIVER_IRUN            {config_vars['AXIS4_DRIVER_IRUN']}",
        f"#define AXIS4_DRIVER_IGOTO           {config_vars['AXIS4_DRIVER_IGOTO']}",
        f"#define AXIS4_DRIVER_STATUS          {config_vars['AXIS4_DRIVER_STATUS']}",
        f"#define AXIS4_DRIVER_DECAY           {config_vars['AXIS4_DRIVER_DECAY']}",
        f"#define AXIS4_DRIVER_DECAY_GOTO      {config_vars['AXIS4_DRIVER_DECAY_GOTO']}",
        f"#define AXIS4_POWER_DOWN             {config_vars['AXIS4_POWER_DOWN']}",
        f"#define AXIS4_SENSE_HOME             {config_vars['AXIS4_SENSE_HOME']}",
        f"#define AXIS4_SENSE_LIMIT_MIN        {config_vars['AXIS4_SENSE_LIMIT_MIN']}",
        f"#define AXIS4_SENSE_LIMIT_MAX        {config_vars['AXIS4_SENSE_LIMIT_MAX']}",
        f"#define FOCUSER_TEMPERATURE           {config_vars['FOCUSER_TEMPERATURE']}",
        "",
        "// AUXILIARY FEATURES"
    ]

    for i in range(1, 9):
        config_lines.extend([
            f"#define FEATURE{i}_PURPOSE            {config_vars[f'FEATURE{i}_PURPOSE']}",
            f"#define FEATURE{i}_NAME              \"{config_vars[f'FEATURE{i}_NAME']}\"",
            f"#define FEATURE{i}_TEMP              {config_vars[f'FEATURE{i}_TEMP']}",
            f"#define FEATURE{i}_PIN               {config_vars[f'FEATURE{i}_PIN']}",
            f"#define FEATURE{i}_VALUE_DEFAULT     {config_vars[f'FEATURE{i}_VALUE_DEFAULT']}",
            f"#define FEATURE{i}_VALUE_MEMORY      {config_vars[f'FEATURE{i}_VALUE_MEMORY']}",
            f"#define FEATURE{i}_ON_STATE          {config_vars[f'FEATURE{i}_ON_STATE']}",
            ""
        ])

    config_lines.extend([
        "#define FileVersionConfig 6",
        "#include \"Extended.config.h\""
    ])

    return "\n".join(config_lines)